name: data_cleanup_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas # for data analysis and manipulation (standard feature)
  - dash # for table manipulation
  - pip
  - pip:
    - dash-mantine-components
    - dash[diskcache]
    - dash_iconify
  - openpyxl # unused
  - lxml # unused
  - xlsxwriter # unused
  - pytest
  - diskcache

  # - numpy # for scientific computing (standard feature) [maybe]
  # - pyscss # for scss to css conversion
  # - matplotlib # for plotting and visualization (bonus feature)
  # - flask # for web development (standard feature)
  # - flask-assets # to manage web assets (standard feature)
  # - beautifulsoup4 # for parsing html and xml files (standard feature)
  # - re # for regular expressions (standard feature) [this is a pythons standard module]
  # - fuzzywuzzy # for fuzzy string matching (standard feature)
  # - python-dateutil # for parsing dates (standard feature)

#* to create the environment, run the following command in the terminal:
  #* conda env create -f environment.yml
#* to update the environment, run the following command in the terminal:
  #* conda env update -f environment.yml
  #* or
  #* conda env update --prune -f environment.yml
#* to activate the environment, run the following command in the terminal:
  #* conda activate data_cleanup_env
